### ISSUE TITLE
I can't run theHarvester in kali linux

### ISSUE THREAD

**Issue by m0kama1** [laramies/theHarvester#1028]
**I can't run theHarvester in kali linux

this is the Error:**
![thHa](https://user-images.githubusercontent.com/35544329/153871904-5ea028cf-2f9c-4123-9a55-a3b628accd49.png)

Traceback (most recent call last):
  File "/usr/bin/theHarvester", line 6, in <module>
    from theHarvester import __main__
  File "/usr/lib/python3/dist-packages/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/usr/lib/python3/dist-packages/theHarvester/discovery/takeover.py", line 1, in <module>
    from theHarvester.lib.core import *
  File "/usr/lib/python3/dist-packages/theHarvester/lib/core.py", line 6, in <module>
    import aiohttp
  File "/usr/lib/python3/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/lib/python3/dist-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str

**Comment by slothfuldog** [comment]
Hi! try to install python3 aiohttp by using this command 

> `sudo apt-get install python3-aiohttp`

hope this helps you!

**Comment by L1ghtn1ng** [comment]
What version of kali are you using?

**Comment by L1ghtn1ng** [comment]
by the sounds of it you are using an old version of theHarvester in kali that did have a packaging bug that got resolved in a new update in kali, but as @slothfuldog pu that would fix your issue
