### ISSUE TITLE
[Bug|Feature Request|Other] Not working in latest kali version

### ISSUE THREAD

**Issue by alonsoir** [laramies/theHarvester#1136]
## Note we do not support installing theHarvester on andriod

**Feature Request or Bug or Other**
 Bug

**Describe the feature request or bug or other**
A clear and concise description of what the bug, feature request,
or other request is.

theHarverster is not working with python 3.9 installed in kali.

**To Reproduce**
Steps to reproduce the behaviour:

```
> theHarvester -d https://www.northernrich.com/ -g
Traceback (most recent call last):
  File "/usr/local/bin/theHarvester", line 4, in <module>
    __import__('pkg_resources').run_script('theHarvester==4.0.3', 'theHarvester')
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1460, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/theHarvester' not found in metadata at '/usr/lib/python3/dist-packages/theHarvester-4.0.3.egg-info'
> python --version
Python 3.9.12

```
**Expected behaviour**
Working with 3.9 version

**System Information (System that tool is running on):**

```
> lsb_release -ra
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.2
Codename:       kali-rolling

```

**Comment by L1ghtn1ng** [comment]
Can you try without the https prefix as that is not needed

**Comment by alonsoir** [comment]
Hi, i have just tried using this command:
```

python3 theHarvester.py -d https://www.northernrich.com/en -g -s -v -n -b all
*******************************************************************
*  _   _                                            _             *                                                                                                                                       
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *                                                                                                                                       
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *                                                                                                                                       
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *                                                                                                                                       
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *                                                                                                                                       
*                                                                 *                                                                                                                                       
* theHarvester 4.0.3                                              *                                                                                                                                       
* Coded by Christian Martorella                                   *                                                                                                                                       
* Edge-Security Research                                          *                                                                                                                                       
* cmartorella@edge-security.com                                   *                                                                                                                                       
*                                                                 *                                                                                                                                       
*******************************************************************                                                                                                                                       
                                                                                                                                                                                                          
                                                                                                                                                                                                          
[*] Target: https://www.northernrich.com/en 
                                                                                                                                                                                                          

[!] Missing API key for Spyse. 

[!] Missing API key for ProjectDiscovery. 

[!] Missing API key for PentestTools. 
[*] Searching Sublist3r. 
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://jldc.me/anubis/subdomains/https://www.northernrich.com/en')
[*] Searching Anubis. 
[*] Searching Hackertarget. 
[*] Searching Threatminer. 
[*] Searching Rocketreach. 
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.n45ht.or.id/v1/subdomain-enumeration?domain=https://www.northernrich.com/en')
[*] Searching Dnsdumpster. 
An exception has occurred: Cannot serialize non-str key 2405946
Google is blocking your ip and the workaround, returning
...
```

So, the code works, with some errors, but it is working.
