### ISSUE TITLE
Getting error when launching theHarvester in ParrotOS

### ISSUE THREAD

**Issue by Wayne-arul** [laramies/theHarvester#1151]
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/usr/lib/python3/dist-packages/theHarvester/__main__.py", line 906, in entry_point
    await start()
  File "/usr/lib/python3/dist-packages/theHarvester/__main__.py", line 60, in start
    args = parser.parse_args()
  File "/usr/lib/python3.9/argparse.py", line 1830, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 1863, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2100, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "/usr/lib/python3.9/argparse.py", line 2587, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.9/argparse.py", line 2574, in exit
    _sys.exit(status)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/theHarvester", line 23, in <module>
    asyncio.run(__main__.entry_point())
  File "/usr/lib/python3.9/asyncio/runners.py", line 49, in run
    loop.run_until_complete(loop.shutdown_default_executor())
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib/python3.9/asyncio/events.py", line 253, in shutdown_default_executor
    raise NotImplementedError
NotImplementedError

**Comment by mercifu1** [comment]
me too i face this problem

**Comment by L1ghtn1ng** [comment]
Can you try it with git version and a virtualenv and does it work correctly for you then? Also does the git version work correctly for you with just using the git code and keeping the dependencies that are installed in the OS?

**Comment by L1ghtn1ng** [comment]
I suspect this is an upstream problem I.E parrot issue

**Comment by RVM1980** [comment]
> Can you try it with git version and a virtualenv and does it work correctly for you then? Also does the git version work correctly for you with just using the git code and keeping the dependencies that are installed in the OS?

This worked for me, all I had to do was do pip3 install -r requirements.txt

**Comment by L1ghtn1ng** [comment]
This is a parrot packaging issue

On 8 Aug 2022, at 11:35, RVM1980 ***@***.***> wrote:

﻿

Can you try it with git version and a virtualenv and does it work correctly for you then? Also does the git version work correctly for you with just using the git code and keeping the dependencies that are installed in the OS?

This worked for me, all I had to do was do pip3 install -r requirements.txt

**Comment by L1ghtn1ng** [comment]
What this comes down to is that this is a parrot packaging issue, I would recommend that you move to kali as it will work correctly on that as trying to get a hold of people for parrot has not worked to get the packaging resolved
