### ISSUE TITLE
Compatibility with Python 3.10

### ISSUE THREAD

**Issue by ocervell** [laramies/theHarvester#1173]
theHarvester breaks on python 3.10:

```
Traceback (most recent call last):
  File "/home/kali/Workspace/theHarvester/theHarvester.py", line 22, in <module>
    from discovery import *
  File "/home/kali/Workspace/theHarvester/discovery/dnssearch.py", line 1, in <module>
    import discovery.IPy as IPy
  File "/home/kali/Workspace/theHarvester/discovery/IPy.py", line 1025, in <module>
    class IPSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
```

**Comment by L1ghtn1ng** [comment]
Do you have an up to date code checkout and up to date dependencies? As I have no issues with python3.10

On 8 Aug 2022, at 12:50, Olivier Cervello ***@***.***> wrote:

﻿

theHarvester breaks on python 3.10:

Traceback (most recent call last):
  File "/home/kali/Workspace/theHarvester/theHarvester.py", line 22, in <module>
    from discovery import *
  File "/home/kali/Workspace/theHarvester/discovery/dnssearch.py", line 1, in <module>
    import discovery.IPy as IPy
  File "/home/kali/Workspace/theHarvester/discovery/IPy.py", line 1025, in <module>
    class IPSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'

**Comment by L1ghtn1ng** [comment]
TImeout
