### ISSUE TITLE
[Bug] Install fails because of missing yaml import

### ISSUE THREAD

**Issue by nopa12** [laramies/theHarvester#1193]
**Installation fails**
Installed using:
```sh
git clone https://github.com/laramies/theHarvester.git
pip install -e ./theHarvester/
```

ended up with:
```sh
      Traceback (most recent call last):
        File "/home/zzz/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/zzz/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/zzz/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-h7vbrpbv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 445, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-h7vbrpbv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-h7vbrpbv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-h7vbrpbv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 482, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-h7vbrpbv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
        File "/home/zzz/theHarvester/theHarvester/lib/core.py", line 4, in <module>
          import yaml
      ModuleNotFoundError: No module named 'yaml'
```

**To Reproduce**
execute:
```sh
git clone https://github.com/laramies/theHarvester.git
pip install -e ./theHarvester/
```

**Expected behaviour**
install will work

**System Information (System that tool is running on):**
Ubuntu 20.04.4 LTS WSL
Python 3.10.5
pyenv

**Detailed info**
`setup.py` imports Core module for the `version` function:
```python
# setup.py
from theHarvester.lib.core import Core
```

`theHarvester/theHarvester/lib/core.py` imports `yaml`:
```python
#theHarvester/theHarvester/lib/core.py
import yaml
```

so that during install, `setup.py` tries to load `yaml` before it's installed (it's indeed included in `base.txt` requirements file)

**Comment by nopa12** [comment]
possible solutions:
a. move `version` function into another module
b. put version as hardcoded part in `setup.py`
c. split the module

if you have a preferred fix let me know and I'd make a PR

**Comment by L1ghtn1ng** [comment]
Do you have this issue on a normal Linux box that is not WSL?

**Comment by L1ghtn1ng** [comment]
The way you are installing is not correct, you will want to run the setup.py which would work and or doing a pip install -r requirements.txt in the theHarvester directory would also do it.

On 24 Aug 2022, at 19:09, nopa12 ***@***.***> wrote:

﻿

possible solutions:
a. move version function into another module
b. put version as hardcoded part in setup.py
c. split the module

if you have a preferred fix let me know and I'd make a PR
