### ISSUE TITLE
Problem: Traceback (most recent call last)

### ISSUE THREAD

**Issue by sandrosana** [laramies/theHarvester#1270]
Problem:

I installed reNgine 1.3.4 and try some feature but i noticed theHarvester didn't work.
This is the error:

_[2022-12-01 08:47:47,382: INFO/ForkPoolWorker-4] OSINT: Getting leaked credentials...
[2022-12-01 08:47:47,525: ERROR/ForkPoolWorker-4] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/usr/src/github/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/usr/src/github/theHarvester/theHarvester/discovery/dnssearch.py", line 17, in <module>
    from theHarvester.lib import hostchecker
  File "/usr/src/github/theHarvester/theHarvester/lib/hostchecker.py", line 14, in <module>
    class Checker:
  File "/usr/src/github/theHarvester/theHarvester/lib/hostchecker.py", line 37, in Checker
    BaseException | Any, BaseException | Any, BaseException | Any, BaseException | Any, BaseException | Any]:
TypeError: unsupported operand type(s) for |: 'type' and '_SpecialForm'
[2022-12-01 08:47:47,629: WARNING/ForkPoolWorker-4] /usr/src/scan_results/eurosystem.it_831526926969/theHarvester.html
[2022-12-01 08:47:47,629: WARNING/ForkPoolWorker-4]_ 

**System Information:** Ubuntu server 22.04
**Python version:** Python 3.8.10

The same error if i try to lounch:
python3 ./theHarvester -h

_root@0fa4e8d6a525:/usr/src/github/theHarvester# python3 ./theHarvester.py -h
Traceback (most recent call last):
  File "./theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/usr/src/github/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/usr/src/github/theHarvester/theHarvester/discovery/dnssearch.py", line 17, in <module>
    from theHarvester.lib import hostchecker
  File "/usr/src/github/theHarvester/theHarvester/lib/hostchecker.py", line 14, in <module>
    class Checker:
  File "/usr/src/github/theHarvester/theHarvester/lib/hostchecker.py", line 37, in Checker
    BaseException | Any, BaseException | Any, BaseException | Any, BaseException | Any, BaseException | Any]:
TypeError: unsupported operand type(s) for |: 'type' and '_SpecialForm' _

**Comment by andre-santos1** [comment]
Same here

**Comment by NotoriousRebel** [comment]
I am not 100% sure of the cause yet, but as a workaround if you comment out this l[ine 37](https://github.com/laramies/theHarvester/blob/master/theHarvester/lib/hostchecker.py#L37) in hostchecker.py where it does the type hinting and rerun the tool, it should work.

**Comment by sandrosana** [comment]
i did it:
_root@0fa4e8d6a525:/usr/src/github/theHarvester# cd theHarvester     
root@0fa4e8d6a525:/usr/src/github/theHarvester/theHarvester# cd lib/
root@0fa4e8d6a525:/usr/src/github/theHarvester/theHarvester/lib# nano hostchecker.py 
root@0fa4e8d6a525:/usr/src/github/theHarvester/theHarvester/lib# cd ..
root@0fa4e8d6a525:/usr/src/github/theHarvester/theHarvester# cd ..
root@0fa4e8d6a525:/usr/src/github/theHarvester# python3 ./theHarvester.py -h
**[!] Make sure you have Python 3.10+ installed, quitting**._

after i installed python 3.10 and.....
the same problem:
_root@0fa4e8d6a525:/usr/src/github/theHarvester# python3.10 ./theHarvester.py -h
Traceback (most recent call last):
  File "/usr/src/github/theHarvester/./theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/usr/src/github/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/usr/src/github/theHarvester/theHarvester/discovery/dnssearch.py", line 14, in <module>
    from aiodns import DNSResolver
ModuleNotFoundError: No module named 'aiodns'_

and i needed to comment the "[" in line 36 and add ":" otherwise the runtime fail

**Comment by L1ghtn1ng** [comment]
All you would need to do to fix the missing module would be to do pip3.10 install -r requirements.txt

On 2 Dec 2022, at 08:54, Sandro ***@***.***> wrote:

﻿

i did it:
***@***.***:/usr/src/github/theHarvester# cd theHarvester
***@***.***:/usr/src/github/theHarvester/theHarvester# cd lib/
***@***.***:/usr/src/github/theHarvester/theHarvester/lib# nano hostchecker.py
***@***.***:/usr/src/github/theHarvester/theHarvester/lib# cd ..
***@***.***:/usr/src/github/theHarvester/theHarvester# cd ..
***@***.***:/usr/src/github/theHarvester# python3 ./theHarvester.py -h
[!] Make sure you have Python 3.10+ installed, quitting.

after i installed python 3.10 and.....
the same problem:
***@***.***:/usr/src/github/theHarvester# python3.10 ./theHarvester.py -h
Traceback (most recent call last):
File "/usr/src/github/theHarvester/./theHarvester.py", line 5, in
from theHarvester import main
File "/usr/src/github/theHarvester/theHarvester/main.py", line 4, in
from theHarvester.discovery import dnssearch, takeover, shodansearch
File "/usr/src/github/theHarvester/theHarvester/discovery/dnssearch.py", line 14, in
from aiodns import DNSResolver
ModuleNotFoundError: No module named 'aiodns'

and i needed to comment the "[" in line 36 and add ":" otherwise the runtime fail

**Comment by sandrosana** [comment]
did it... 

Same error... 
i think the problem can be python, if i deploy theharvester on kali linux (last version) all works good.

**Comment by L1ghtn1ng** [comment]
Seems it is a rengine issue then?

**Comment by sandrosana** [comment]
no. If i install on:
System Information: Ubuntu server 22.04
Python version: Python 3.8.10

i've the same problem.

**Comment by L1ghtn1ng** [comment]
Ubuntu 22.04 has python3.10 by default so I do not know how you have python3.8 on it, the only thing I can think of is do sudo apt autoremove -y and see if it removes it otherwise doing sudo apt install python3.10 will fix that issue

On 2 Dec 2022, at 16:04, Sandro ***@***.***> wrote:

﻿

no. If i install on:
System Information: Ubuntu server 22.04
Python version: Python 3.8.10

i've the same problem.

**Comment by sandrosana** [comment]
OK, i solved...
I installed Python version 3.8.10 on Docker of renGine...

Thanks

**Comment by barbixxxa** [comment]
Same problem here

python --version           
```
Python 3.8.10
```

pip --version
```
pip 22.3.1 from /root/tools/theHarvester-virtualEnv/lib/python3.8/site-packages/pip (python 3.8)
```

python theHarvester.py -h
```
Traceback (most recent call last):
  File "theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/root/tools/theHarvester-virtualEnv/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/root/tools/theHarvester-virtualEnv/theHarvester/theHarvester/discovery/dnssearch.py", line 17, in <module>
    from theHarvester.lib import hostchecker
  File "/root/tools/theHarvester-virtualEnv/theHarvester/theHarvester/lib/hostchecker.py", line 14, in <module>
    class Checker:
  File "/root/tools/theHarvester-virtualEnv/theHarvester/theHarvester/lib/hostchecker.py", line 37, in Checker
    BaseException | Any, BaseException | Any, BaseException | Any, BaseException | Any, BaseException | Any]:
TypeError: unsupported operand type(s) for |: 'type' and '_SpecialForm'
```

**Comment by L1ghtn1ng** [comment]
It should work correctly for you with python3.10 if you can create pyenv for theHarvester to use and a 3.10 virtualenv for the dependencies
