### ISSUE TITLE
[Bug] Error while running theHarvester in ParrotOS

### ISSUE THREAD

**Issue by ImSronistic** [laramies/theHarvester#1285]
theHarvester: error: the following arguments are required: -d/--domain
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/usr/lib/python3/dist-packages/theHarvester/__main__.py", line 830, in entry_point
    await start()
  File "/usr/lib/python3/dist-packages/theHarvester/__main__.py", line 57, in start
    args = parser.parse_args()
  File "/usr/lib/python3.9/argparse.py", line 1830, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 1863, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2100, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "/usr/lib/python3.9/argparse.py", line 2587, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.9/argparse.py", line 2574, in exit
    _sys.exit(status)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/theHarvester", line 28, in <module>
    asyncio.run(__main__.entry_point())
  File "/usr/lib/python3.9/asyncio/runners.py", line 49, in run
    loop.run_until_complete(loop.shutdown_default_executor())
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib/python3.9/asyncio/events.py", line 253, in shutdown_default_executor
    raise NotImplementedError
NotImplementedError

Tried with -d, -h or without Option, still showing same error.
Python 3.9.2 & ParrotOS 5.1 ara

**Comment by L1ghtn1ng** [comment]
This is a parrot packaging issue, please report to them that they have missed required dependencies that are needed for theHarvester to work. In the meantime you will need to use a virtualenv to get it to work on parrot which can be found how to set that up on the wiki, but it will require having python 3.10+ being installed.  What I recommend if you want a simple way to get it to work is move to kali as that does not have this issue. I have tried reaching out to parrot to get this resolved but no one came back to me.

Thanks,
Jay

On 18 Dec 2022, at 04:51, HeySrone ***@***.***> wrote:

﻿

theHarvester: error: the following arguments are required: -d/--domain
Traceback (most recent call last):
File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
File "/usr/lib/python3/dist-packages/theHarvester/main.py", line 830, in entry_point
await start()
File "/usr/lib/python3/dist-packages/theHarvester/main.py", line 57, in start
args = parser.parse_args()
File "/usr/lib/python3.9/argparse.py", line 1830, in parse_args
args, argv = self.parse_known_args(args, namespace)
File "/usr/lib/python3.9/argparse.py", line 1863, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
File "/usr/lib/python3.9/argparse.py", line 2100, in parse_known_args
self.error(('the following arguments are required: %s') %
File "/usr/lib/python3.9/argparse.py", line 2587, in error
self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
File "/usr/lib/python3.9/argparse.py", line 2574, in exit
_sys.exit(status)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/theHarvester", line 28, in
asyncio.run(main.entry_point())
File "/usr/lib/python3.9/asyncio/runners.py", line 49, in run
loop.run_until_complete(loop.shutdown_default_executor())
File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
File "/usr/lib/python3.9/asyncio/events.py", line 253, in shutdown_default_executor
raise NotImplementedError
NotImplementedError

Tried with -d, -h or without Option, still showing same error.
Python 3.9.2 & ParrotOS 5.1 ara

**Comment by ImSronistic** [comment]
Yes, It's working in Kali. thanks for the help.

**Comment by L1ghtn1ng** [comment]
I have managed to get hold of people at parrot so this will be resolved in the near future so be on the lookout for a package update that will fix this moving forward
