### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Deskord** [laramies/theHarvester#146]
[-] Searching in Google.
	Searching 0 results...
	Searching 100 results...
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "theHarvester.py", line 847, in <module>
    start(sys.argv[1:])
  File "theHarvester.py", line 185, in start
    search.process(google_dorking)
  File "/home/deskord/Documents/theHarvester/discovery/googlesearch.py", line 76, in process
    self.do_search()
  File "/home/deskord/Documents/theHarvester/discovery/googlesearch.py", line 32, in do_search
    self.results = r.text
UnboundLocalError: local variable 'r' referenced before assignment
None

**Comment by Deskord** [comment]
I decided everything Sorry

**Comment by Deskord** [comment]
I decided everything Sorry

**Comment by leebaird** [comment]
This can be closed.

**Comment by NotoriousRebel** [comment]
As this is on user end closing! The tool works properly when a stable internet connection is available.
