### ISSUE TITLE
command line parameter order matters

### ISSUE THREAD

**Issue by digininja** [laramies/theHarvester#159]
The order of the parameters on the command line matters, running with `-b` first causes an error:

```
$ ./theHarvester.py  -b all -l 10 -d digi.ninja

*******************************************************************
*  _   _                                            _             *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* theHarvester 3.0.6 v183                                         *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*                                                                 *
******************************************************************* 

 
Traceback (most recent call last):
  File "./theHarvester.py", line 919, in <module>
    start(sys.argv[1:])
  File "./theHarvester.py", line 104, in start
    print(f'\033[94m[*] Target domain: {word} \n \033[0m')
UnboundLocalError: local variable 'word' referenced before assignment
None
```

But swapping it to the end works fine:

```
$ ./theHarvester.py  -l 10 -d digi.ninja -b all

*******************************************************************
*  _   _                                            _             *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* theHarvester 3.0.6 v183                                         *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*                                                                 *
******************************************************************* 

 
[*] Target domain: digi.ninja 
 
Full harvest on digi.ninja
[*] Searching Baidu.
^C

[!] ctrl+c detected from user, quitting.
```

It also fails with it in the middle so I'm guessing it is the parsing of the multiple values you can pass to `-b` that causes the problem.

**Comment by leebaird** [comment]
Thanks digininja. We are aware and working on a fix.
