### ISSUE TITLE
wont fun on kali linux get error message

### ISSUE THREAD

**Issue by Darkcast** [laramies/theHarvester#16]
Traceback (most recent call last):
  File "theHarvester.py", line 10, in <module>
    from discovery import *
  File "/root/Downloads/theHarvester-master/discovery/googlesearch.py", line 6, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 55, in <module>
    orig_connectionpool_ssl_wrap_socket = connectionpool.ssl_wrap_socket
AttributeError: 'module' object has no attribute 'ssl_wrap_socket'

**Comment by laramies** [comment]
Hi Darkcast, seems that it is a problem in your pyopenssl installation. theHarvester is trying to import the requests library, and requests fails to import pyopenssl. No idea how to fix it. :/

**Comment by darker0n** [comment]
You can try:

        pip install pyopenssl

or:

       pip install urllib3
