### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by koubaabdellah** [laramies/theHarvester#1601]
`/Tools/theHarvester# python3 theHarvester.py -h
Read proxies.yaml from /root/.theHarvester/proxies.yaml
Traceback (most recent call last):
  File "theHarvester.py", line 5, in <module>
    from theHarvester.theHarvester import main
  File "/root/Tools/theHarvester/theHarvester/theHarvester.py", line 4, in <module>
    from theHarvester import __main__
  File "/root/Tools/theHarvester/theHarvester/__main__.py", line 16, in <module>
    from theHarvester.discovery import (
  File "/root/Tools/theHarvester/theHarvester/discovery/securitytrailssearch.py", line 6, in <module>
    from theHarvester.parsers import securitytrailsparser
  File "/root/Tools/theHarvester/theHarvester/parsers/securitytrailsparser.py", line 4, in <module>
    class Parser:
  File "/root/Tools/theHarvester/theHarvester/parsers/securitytrailsparser.py", line 11, in Parser
    async def parse_text(self) -> tuple[set, set]:
TypeError: 'type' object is not subscriptable
`

**Comment by koubaabdellah** [comment]
`Traceback (most recent call last):
  File "theHarvester.py", line 5, in <module>
    from theHarvester.theHarvester import main
  File "/root/Tools/theHarvester/theHarvester/theHarvester.py", line 4, in <module>
    from theHarvester import __main__
  File "/root/Tools/theHarvester/theHarvester/__main__.py", line 16, in <module>
    from theHarvester.discovery import (
  File "/root/Tools/theHarvester/theHarvester/discovery/securitytrailssearch.py", line 6, in <module>
    from theHarvester.parsers import securitytrailsparser
  File "/root/Tools/theHarvester/theHarvester/parsers/securitytrailsparser.py", line 4, in <module>
    class Parser:
  File "/root/Tools/theHarvester/theHarvester/parsers/securitytrailsparser.py", line 11, in Parser
    async def parse_text(self) -> tuple[set, set]:
TypeError: 'type' object is not subscriptable
`

**Comment by jryebread** [comment]
same here when i try to run the python file

**Comment by NotoriousRebel** [comment]
@jryebread @koubaabdellah Apologies for the late response, it seems to be a mistyping on line https://github.com/laramies/theHarvester/blob/master/theHarvester/parsers/securitytrailsparser.py#L11 `tuple[set, set]:` should be `Tuple[set, set]:` That should fix the error you are running into
