### ISSUE TITLE
Issues to run theHarvester

### ISSUE THREAD

**Issue by vectorexpl** [laramies/theHarvester#1675]
Hi,
I get the following messages while trying to run theHarvester
─$ theHarvester -h
Traceback (most recent call last):
  File "/usr/bin/theHarvester", line 5, in <module>
    from theHarvester.theHarvester import main
  File "/usr/lib/python3/dist-packages/theHarvester/theHarvester.py", line 4, in <module>
    from theHarvester import __main__
  File "/usr/lib/python3/dist-packages/theHarvester/__main__.py", line 16, in <module>
    from theHarvester.discovery import (
  File "/usr/lib/python3/dist-packages/theHarvester/discovery/anubis.py", line 1, in <module>
    from theHarvester.lib.core import AsyncFetcher
  File "/usr/lib/python3/dist-packages/theHarvester/lib/core.py", line 271, in <module>
    class AsyncFetcher:
  File "/usr/lib/python3/dist-packages/theHarvester/lib/core.py", line 272, in AsyncFetcher
    proxy_list = Core.proxy_list()
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/theHarvester/lib/core.py", line 138, in proxy_list
    keys = yaml.safe_load(Core._read_config("proxies.yaml"))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/theHarvester/lib/core.py", line 35, in _read_config
    config = file.read_text()
             ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1059, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1045, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/etc/theHarvester/proxies.yaml'

## Note we do not support installing theHarvester on android

**Feature Request or Bug or Another**
Feature Request | Bug | Other

**Describe the feature request or bug or other**
A clear and concise description of what the bug, feature request,
or other request is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: '...'
2. See error

**Expected behaviour**

**Screenshots**
If possible please add screenshots to help explain your problem.

**System Information (System that tool is running on):**
 - OS: [e.g. Windows10]
 - Version [e.g. 2.7]

**Additional context**

**Comment by L1ghtn1ng** [comment]
What version of the tool do you have and what OS you on?

On 2 Mar 2024, at 10:09, vectorexpl ***@***.***> wrote:

﻿

Hi,
I get the following messages while trying to run theHarvester
─$ theHarvester -h
Traceback (most recent call last):
File "/usr/bin/theHarvester", line 5, in
from theHarvester.theHarvester import main
File "/usr/lib/python3/dist-packages/theHarvester/theHarvester.py", line 4, in
from theHarvester import main
File "/usr/lib/python3/dist-packages/theHarvester/main.py", line 16, in
from theHarvester.discovery import (
File "/usr/lib/python3/dist-packages/theHarvester/discovery/anubis.py", line 1, in
from theHarvester.lib.core import AsyncFetcher
File "/usr/lib/python3/dist-packages/theHarvester/lib/core.py", line 271, in
class AsyncFetcher:
File "/usr/lib/python3/dist-packages/theHarvester/lib/core.py", line 272, in AsyncFetcher
proxy_list = Core.proxy_list()
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/theHarvester/lib/core.py", line 138, in proxy_list
keys = yaml.safe_load(Core._read_config("proxies.yaml"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/theHarvester/lib/core.py", line 35, in _read_config
config = file.read_text()
^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/pathlib.py", line 1059, in read_text
with self.open(mode='r', encoding=encoding, errors=errors) as f:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/pathlib.py", line 1045, in open
return io.open(self, mode, buffering, encoding, errors, newline)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/etc/theHarvester/proxies.yaml'

Note we do not support installing theHarvester on android

Feature Request or Bug or Another
Feature Request | Bug | Other

Describe the feature request or bug or other
A clear and concise description of what the bug, feature request,
or other request is.

To Reproduce
Steps to reproduce the behaviour:

  1.  Run tool like this: '...'
  2.  See error

Expected behaviour
A clear and concise description of what you expected to happen.

Screenshots
If possible please add screenshots to help explain your problem.

System Information (System that tool is running on):

  *   OS: [e.g. Windows10]
  *   Version [e.g. 2.7]

Additional context
Add any other context about the problem here.

**Comment by vectorexpl** [comment]
Hi,
Thanks for your reply.
I have the 4.5.1 version on Kali Linux.

**Comment by L1ghtn1ng** [comment]
I just setup a fresh kali vm and I cannot replicate your issue at all, if you are using a kali vm get the latest net installer image and use that. The only other thing I can think of is update your system, to see if that fixes your issue. At the moment it seems to be a local only issue and not a code issue.

On 2 Mar 2024, at 15:56, vectorexpl ***@***.***> wrote:

﻿

Hi,
Thanks for your reply.
I have the 4.5.1 version on Kali Linux.

**Comment by vectorexpl** [comment]
Thank you for your reply and feedback. I use the latest Kali image and everything is updated.

**Comment by L1ghtn1ng** [comment]
Closing this out as I cannot reproduce this at all the only other option you have really is to install from git using pipx

**Comment by vectorexpl** [comment]
Thanks for the suggestion.
