### ISSUE TITLE
Unable to Install on Debian 7

### ISSUE THREAD

**Issue by YashvirGit** [laramies/theHarvester#222]
I have the latest Python3.7.2 installed. I'm on Debian 7 64bit
Here's how I tried install 
git clone https://github.com/laramies/theHarvester.git
cd theHarvester
ls
pip3 install -r requirements.txt
python3 theHarvester.py
Why it won't work
![Screenshot from 2019-03-13 22-13-05](https://user-images.githubusercontent.com/48529728/54326700-bae55400-4620-11e9-873c-b257d729d321.png)

**Comment by YashvirGit** [comment]
root@kali:~/Desktop/theHarvester# ./theHarvester.py
Traceback (most recent call last):
  File "./theHarvester.py", line 7, in <module>
    from lib import reportgraph
  File "/root/Desktop/theHarvester/lib/reportgraph.py", line 2, in <module>
    from lib import stash
  File "/root/Desktop/theHarvester/lib/stash.py", line 2, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by NotoriousRebel** [comment]
If you are using python3.4+ pip should already be on it; however, you could try ```sudo apt-get install python3-pip``` and then do ```sudo pip3 install -r requirements.txt```

**Comment by YashvirGit** [comment]
> If you are using python3.4+ pip should already be on it; however, you could try `sudo apt-get install python3-pip` and then do `sudo pip3 install -r requirements.txt`

Yo bro i already installed the requirements and everything was Done Done Done Done 
but yet i got the same Yaml Error 
i tried on Windows 10 also same Yaml Error Module


C:\Python37\theHarvester>theHarvester.py
Traceback (most recent call last):
  File "C:\Python37\theHarvester\theHarvester.py", line 3, in <module>
    from discovery import *
  File "C:\Python37\theHarvester\discovery\baidusearch.py", line 2, in <module>
    from lib.core import *
  File "C:\Python37\theHarvester\lib\core.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

C:\Python37\theHarvester>

**Comment by NotoriousRebel** [comment]
Show me the error message you get when trying to do ```sudo python3 -m pip install -r requirements.txt``` on kali.

**Comment by L1ghtn1ng** [comment]
Timeout

**Comment by FabioJorgeJesus** [comment]
Hello to everyone.
after clone theharvester ion my Kali Linux, it show me the message below:
Traceback (most recent call last):
  File "./theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/root/theHarvester/theHarvester/__main__.py", line 3, in <module>
    from theHarvester.discovery import *
  File "/root/theHarvester/theHarvester/discovery/baidusearch.py", line 2, in <module>
    from theHarvester.lib.core import *
  File "/root/theHarvester/theHarvester/lib/core.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

Have you any idea what´s happening?

**Comment by L1ghtn1ng** [comment]
you need to either do apt install python3-pyyaml or pip3 install -r requirements.txt

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
