### ISSUE TITLE
Error in start script

### ISSUE THREAD

**Issue by vincenzogianfelice** [laramies/theHarvester#259]
```
Traceback (most recent call last):
  File "theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/opt/theHarvester/theHarvester/__main__.py", line 96
    print(f'\033[94m[*] Target: {word} \n \033[0m')
```

**Comment by L1ghtn1ng** [comment]
Hi you need to be running python3.6+

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by L1ghtn1ng** [comment]
If you do a git pull this should now be fixed
