### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by paradiseduo** [laramies/theHarvester#269]
➜  theHarvester git:(master) ✗ ./theHarvester.py
Traceback (most recent call last):
  File "./theHarvester.py", line 10, in <module>
    from theHarvester import __main__
  File "/Users/youshaoduo/Desktop/TestTools/theHarvester/theHarvester/__main__.py", line 7, in <module>
    from theHarvester.lib import reportgraph
  File "/Users/youshaoduo/Desktop/TestTools/theHarvester/theHarvester/lib/reportgraph.py", line 5, in <module>
    import plotly.plotly as py
  File "/usr/local/lib/python3.7/site-packages/plotly/plotly/__init__.py", line 4, in <module>
    _chart_studio_error("plotly")
  File "/usr/local/lib/python3.7/site-packages/_plotly_future_/__init__.py", line 49, in _chart_studio_error
    submodule=submodule
ImportError:
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.

MacOS 10.14.5    Python3.7.4

**Comment by littl3field** [comment]
Hi, there is a solution for this. 
When using Plotly version 4 you will get this error. 
You can downgrade to version 3.10.0 to fix this this. 

Simply run:

`pip3 install plotly==3.10.0`

This will fix your problem.

**Comment by sieunhando** [comment]
Or change `import plotly.plotly as py` to `import chart_studio.plotly as py` at `theHarvester/lib/reportgraph.py`

**Comment by L1ghtn1ng** [comment]
Closing due to being a duplicate

**Comment by L1ghtn1ng** [comment]
I have a pr that will fix this once merged
________________________________
