### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by 0xn0ne** [laramies/theHarvester#283]
em... what can I say

**Command:** proxychains python3 theHarvester.py -d xxx.xx -b all

**Issues:**
Traceback (most recent call last):
  File "/home/xn0ne/theHarvester/theHarvester/__main__.py", line 943, in entry_point
    start()
  File "/home/xn0ne/theHarvester/theHarvester/__main__.py", line 426, in start
    search.process()
  File "/home/xn0ne/theHarvester/theHarvester/discovery/crtsh.py", line 22, in process
    data = self.do_search()
  File "/home/xn0ne/theHarvester/theHarvester/discovery/crtsh.py", line 18, in do_search
    return data
UnboundLocalError: local variable 'data' referenced before assignment

**Fix:**

the variable "data" is not initialized in code.

`$ vim /home/xxxx/theHarvester/theHarvester/discovery/crtsh.py`

insert 15 line before: `data = None`

![image](https://user-images.githubusercontent.com/16507416/63632989-a4353580-c673-11e9-866d-abb73aff0c4c.png)

**Comment by 0xn0ne** [comment]
I think this is just a question of variable scope

**Comment by L1ghtn1ng** [comment]
This should be fixed in master now
