### ISSUE TITLE
intelx

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#303]
OS: Running on Kali Linux, fully patched with the latest version of the repo.
Target: livenation.com
module: intelx

Traceback (most recent call last):
  File "/usr/lib/python3.7/encodings/idna.py", line 167, in encode
    raise UnicodeError("label too long")
UnicodeError: label too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gevent/threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)
2019-09-16T23:59:50Z (<ThreadPool at 0x7f4a81147c10 0/1/10 hub=<Hub at 0x7f4a85de2950 thread_ident=0x139958095013696>>, <built-in function gethostbyname>) failed with UnicodeError

**Comment by L1ghtn1ng** [comment]
@NotoriousRebel What is the update on this one?

**Comment by NotoriousRebel** [comment]
@L1ghtn1ng This has been resolved in the most recent PR to your fork.

**Comment by L1ghtn1ng** [comment]
closing as this will be solved in master shortly

**Comment by LzyRapx** [comment]
@NotoriousRebel  hi, would you tell me which PR solved this issue? Thanks in advance.

**Comment by L1ghtn1ng** [comment]
If you are experiencing this issue please git clone and that will fix you issue
