### ISSUE TITLE
Issues with app on Arch Linux

### ISSUE THREAD

**Issue by ssolidus** [laramies/theHarvester#305]
I manage the Arch Linux package for this app:

https://aur.archlinux.org/packages/theharvester-git/

https://aur.archlinux.org/packages/python-theharvester-git/

As of a recent version, I get this error:

```
~ theharvester                                      
Traceback (most recent call last):
  File "/opt/theharvester-git/theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/opt/theharvester-git/theHarvester/__main__.py", line 7, in <module>
    from theHarvester.lib import reportgraph
  File "/opt/theharvester-git/theHarvester/lib/reportgraph.py", line 5, in <module>
    import plotly.plotly as py
  File "/usr/lib/python3.7/site-packages/plotly/plotly/__init__.py", line 4, in <module>
    _chart_studio_error("plotly")
  File "/usr/lib/python3.7/site-packages/_plotly_future_/__init__.py", line 49, in _chart_studio_error
    submodule=submodule
ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 
```

Could you please advise? Arch Linux doesn't have the `python-chart-studio` package, but I've made packages in the past that were dependencies of theHarvester, and wouldn't mind doing that. However I think that the code would need to be modified as well.

**Comment by L1ghtn1ng** [comment]
If you get the very most recent checkout of git this issue is resolved
________________________________

**Comment by ssolidus** [comment]
I fixed this by clean-installing the package, which produced new errors, which were fixed by adding the dependencies with `python-gevent` and `python-grequests`
