### ISSUE TITLE
unable to start v3.1

### ISSUE THREAD

**Issue by blshkv** [laramies/theHarvester#344]
I have installed the latest version 3.1 using setup.py and tried to run it. Here is the the full output:
```
theHarvester -d test.com
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/theHarvester", line 11, in <module>
    load_entry_point('theHarvester==3.0.6', 'console_scripts', 'theHarvester')()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.6/site-packages/theHarvester/__main__.py", line 7, in <module>
    from theHarvester.lib import reportgraph
  File "/usr/lib64/python3.6/site-packages/theHarvester/lib/reportgraph.py", line 3, in <module>
    import plotly
  File "/usr/lib64/python3.6/site-packages/plotly/__init__.py", line 31, in <module>
    from plotly import (plotly, graph_objs, grid_objs, tools, utils, session,
  File "/usr/lib64/python3.6/site-packages/plotly/plotly/__init__.py", line 10, in <module>
    from . plotly import (
  File "/usr/lib64/python3.6/site-packages/plotly/plotly/plotly.py", line 31, in <module>
    from plotly import exceptions, tools, utils, version, files
  File "/usr/lib64/python3.6/site-packages/plotly/tools.py", line 20, in <module>
    from plotly import graph_reference
  File "/usr/lib64/python3.6/site-packages/plotly/graph_reference.py", line 518, in <module>
    GRAPH_REFERENCE = get_graph_reference()
  File "/usr/lib64/python3.6/site-packages/plotly/graph_reference.py", line 86, in get_graph_reference
    sha1 = hashlib.sha1(six.b(str(graph_reference))).hexdigest()
  File "/usr/lib64/python3.6/site-packages/six.py", line 626, in b
    return s.encode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u25b2' in position 1455722: ordinal not in range(256)
```

**Comment by blshkv** [comment]
my bad, wrong (test) version
