### ISSUE TITLE
Error when launch theHarvester -h

### ISSUE THREAD

**Issue by samcodesign** [laramies/theHarvester#415]
`Traceback (most recent call last):
  File "/usr/bin/theHarvester", line 11, in <module>
    load_entry_point('theHarvester==3.1.0', 'console_scripts', 'theHarvester')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/theHarvester/__main__.py", line 6, in <module>
    from theHarvester.lib import reportgraph
  File "/usr/lib/python3/dist-packages/theHarvester/lib/reportgraph.py", line 3, in <module>
    import plotly
  File "/usr/local/lib/python3.7/dist-packages/plotly/__init__.py", line 30, in <module>
    from plotly import (
  File "/usr/local/lib/python3.7/dist-packages/plotly/graph_objs/__init__.py", line 100294, in <module>
    if LooseVersion(ipywidgets.__version__) >= LooseVersion("7.0.0"):
AttributeError: module 'ipywidgets' has no attribute '__version__'
` (parrot OS)

**Comment by KyuCore** [comment]
_but it works when I launch it with pipenv_

**Comment by L1ghtn1ng** [comment]
This seems to be from what I can tell a parrotOS issue not a harvester issue. Will have a look though
________________________________

**Comment by MMustafa53** [comment]
sudo -H pip3 install -U pip plotly ipywidgets
(without pipenv)
that works for me :))

**Comment by L1ghtn1ng** [comment]
As parrotOS is using Kali packages it seems it is a Kali bug as I have not run into this issue with pipenv virtual environment
________________________________

**Comment by MMustafa53** [comment]
i get error from ipywidgets in parrotOS and solve it update it.

**Comment by L1ghtn1ng** [comment]
Yeah I got that as well when I checked it out, I was thinking possibly needs a package update to resolve it

________________________________

**Comment by samcodesign** [comment]
Thank you for your help!

**Comment by RohanMahakal1410** [comment]
Thank You

**Comment by atmoner** [comment]
> sudo -H pip3 install -U pip plotly ipywidgets
> (without pipenv)
> that works for me :))

Work =)

**Comment by L1ghtn1ng** [comment]
Yeah thought they needed new version of the packages pulled into there repos bit you doing that can break your system if you are not careful

**Comment by CpoSaint** [comment]
theHarvester -h
Traceback (most recent call last):
  File "/usr/bin/theHarvester", line 6, in <module>
    from theHarvester import __main__
  File "/usr/lib/python3/dist-packages/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/usr/lib/python3/dist-packages/theHarvester/discovery/takeover.py", line 1, in <module>
    from theHarvester.lib.core import *
  File "/usr/lib/python3/dist-packages/theHarvester/lib/core.py", line 6, in <module>
    import aiohttp
  File "/usr/lib/python3/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/lib/python3/dist-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str

**Comment by deepakdubey8756** [comment]
Got same error. Don't know how to fix it. please help

**Comment by icass** [comment]
Eat shit
