### ISSUE TITLE
python3 theHarvester.py -h Launch Error

### ISSUE THREAD

**Issue by lok-esh** [laramies/theHarvester#462]
Traceback (most recent call last):                                                              File "theHarvester.py", line 12, in <module>                                                    from theHarvester import __main__
  File "/data/data/com.termux/files/home/theHarvester/theHarvester/__main__.py", line 3, in <module>
    from theHarvester.discovery import *                                                        File "/data/data/com.termux/files/home/theHarvester/theHarvester/discovery/dnssearch.py", line 14, in <module>                                                                                from aiodns import DNSResolver
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/aiodns/__init__.py", line 4, in <module>                                                                                    import pycares                                                                              File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pycares/__init__.py", line 2, in <module>                                                                                   from ._cares import ffi as _ffi, lib as _lib
ImportError: dlopen failed: cannot locate symbol "getservbyport_r" referenced by "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pycares/_cares.cpython-38.so"...

On Termux

**Comment by NotoriousRebel** [comment]
1. Are you using the latest version of the tool?
2. Did you follow the instructions properly on the [installation page](https://github.com/laramies/theHarvester/wiki/Installation) in the wiki

**Comment by 10ke5h** [comment]
I'd tried everything freshly for 3 times and each time the same error don't know what's happening...

**Comment by NotoriousRebel** [comment]
hmmm ok have you seen [this](https://github.com/termux/termux-packages/issues/4778)?

**Comment by 10ke5h** [comment]
I didn't got that what found that file "config_android" mentioned over there please help me what should I do...

**Comment by yippiez** [comment]
deps/c-ares/src/config_android/ares_config.h you have to go to this file and comment out   HAVE_GETSERVBYPORT.

`
#define HAVE_GETSERVBYPORT_R 1 
`

Should be:

` //#define HAVE_GETSERVBYPORT_R 1
`

**Comment by L1ghtn1ng** [comment]
Closing this as this seems to do with Android and this is not something we support
