### ISSUE TITLE
No module named  'yaml'

### ISSUE THREAD

**Issue by Atharva-Kothawade** [laramies/theHarvester#471]
I have followed every step properly in the wiki and have install yaml too using "apt-get install python3-yaml" but after using "python3 theHarvester.py" it still shows No module named yaml.

**Comment by Atharva-Kothawade** [comment]
root@kali:~# cd theHarvester
root@kali:~/theHarvester# python3 theHarvester.py
Traceback (most recent call last):
  File "theHarvester.py", line 12, in <module>
    from theHarvester import __main__
  File "/root/theHarvester/theHarvester/__main__.py", line 3, in <module>
    from theHarvester.discovery import *
  File "/root/theHarvester/theHarvester/discovery/baidusearch.py", line 1, in <module>
    from theHarvester.lib.core import *
  File "/root/theHarvester/theHarvester/lib/core.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
**THIS MIGHT HELP**

**Comment by NotoriousRebel** [comment]
How did you install the tool?

**Comment by Atharva-Kothawade** [comment]
from the wiki (without pipenv)
