### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by sundruid** [laramies/theHarvester#500]
Setup was straightforward, but with first query, get this error:

Any ideas? Does this need to be fixed in the documentation if this is a silly user error?

Command -- > python3 theHarvester.py -d google.com -b otx

returning exception unable to open database file
Traceback (most recent call last):
  File "/home/k/.local/share/virtualenvs/theHarvester-JS0JuziM/lib/python3.8/site-packages/aiosqlite/core.py", line 95, in run
    result = function()
  File "/home/k/.local/share/virtualenvs/theHarvester-JS0JuziM/lib/python3.8/site-packages/aiosqlite/core.py", line 346, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file

**Comment by sundruid** [comment]
This is an issue where the git clone was done with sudo or as root and then ran by a normal user. Delete theHarvester directory and reinstall without sudo and should work fine.
