### ISSUE TITLE
[Bug|Feature Request|Other] Short Description of Issue

### ISSUE THREAD

**Issue by oshadabasnayake** [laramies/theHarvester#682]
# Error in theHarvester (_main_.entry_point())
## error :point_down:
^CTraceback (most recent call last):
  File "/usr/bin/theHarvester", line 28, in <module>
    asyncio.run(__main__.entry_point())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/handles/poll.pyx", line 213, in uvloop.loop.__on_uvpoll_event
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 73, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 359, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 364, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 339, in uvloop.loop.Loop._ceval_process_signals
KeyboardInterrupt

################

**Feature Request or Bug or Other**
Feature Request | Bug | Other | Code error

**Describe the feature request or bug or other**

1. Choosing the attacking browsers  with comma searation.
2. Google API Problem

**To Reproduce**
Steps to reproduce the behaviour:

1. error correction in harvester core
2. Enhanced or alternate Google api pronlem

**Expected behaviour**
Better error handling and code of conduct

 

**System Information (System that tool is running on):**
 - OS: [Linux]
 - Version [_]

**Additional context**
Recheck the programme

**Comment by L1ghtn1ng** [comment]
That is not an issue error its just the traceback for doing CTRL+C that is all
