### ISSUE TITLE
[Bug] Require pip3 version>=20.3 to install orjson 3.6.3

### ISSUE THREAD

**Issue by tuantmb** [laramies/theHarvester#847]
**Bug**
Require pip3 version>=20.3 to install orjson 3.6.3

**Describe the bug**
I'm using Debian 10 (buster) with python3.7 (pip version 18.1) and I can't install the harvester as the guide in [wiki document](https://github.com/laramies/theHarvester/wiki/Installation). It always failed when installing orjson 3.6.3 with the following message
```
Collecting netaddr==0.8.0 (from -r requirements/base.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/ff/cd/9cdfea8fc45c56680b798db6a55fa60a22e2d3d3ccf54fc729d083b50ce4/netaddr-0.8.0-py2.py3-none-any.whl
Collecting orjson==3.6.3 (from -r requirements/base.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/92/97/895dfe0c2e7820fd5453d0efab6a9036de7f97b4edfd157a6a414dd3b0ee/orjson-3.6.3.tar.gz (746kB)
    100% |████████████████████████████████| 747kB 1.8MB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-2nnbci1q/orjson/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2nnbci1q/orjson/
```
So I tried to install orjson from [orjson github](https://github.com/ijl/orjson)and got the following usage:
```
Install
To install a wheel from PyPI:

pip install --upgrade "pip>=20.3" # manylinux_x_y, universal2 wheel support
pip install --upgrade orjson
```

**To Reproduce**
1. Install pip(3) version <20.3
```shell
python3 -m pip install pip==18.1
```
2. Install theharvester by source code from github (see wiki document for more details)
3. You will get the following error
```
Downloading https://files.pythonhosted.org/packages/92/97/895dfe0c2e7820fd5453d0efab6a9036de7f97b4edfd157a6a414dd3b0ee/orjson-3.6.3.tar.gz (746kB)
    100% |████████████████████████████████| 747kB 1.8MB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-{RANDOM}/orjson/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-{RANDOM}/orjson/
```

**Expected behavior**
Install successfully with the guide in the [wiki](https://github.com/laramies/theHarvester/wiki/Installation)

**System Information (System that tool is running on):**
 - OS: Debian 10 (Buster)
 - Version: Python 3.7.3, pip 18.1, theHarvester master branch (05/09/2021)

**How to fix**
Add require *"pip>=20.3"* to requirements files *(base.txt, dev.txt)*: 
```console
cat requirements/base.txt

pip>=20.3
aiodns==3.0.0
aiofiles==0.7.0
aiohttp==3.7.4.post0
aiomultiprocess==0.9.0
aiosqlite==0.17.0
beautifulsoup4==4.9.3
censys==2.0.6
certifi==2021.05.30
dnspython==2.1.0
fastapi==0.68.1
netaddr==0.8.0
orjson==3.6.3
pyppeteer==0.2.6
PyYAML==5.4.1
requests==2.26.0
retrying==1.3.3
setuptools==57.4.0
shodan==1.25.0
slowapi==0.1.5
starlette==0.14.2
lxml==4.6.3
uvicorn==0.15.0
uvloop==0.16.0; platform_system != "Windows"
```

or update installation guide to pre-install *pip>=20.3* for *orjson*

**Comment by NotoriousRebel** [comment]
Thank you for creating this issue, if you would like you could create a PR with edits to the wiki in case other people run into this issue :)

**Comment by L1ghtn1ng** [comment]
Added this to the wiki, thanks
