### ISSUE TITLE
[Bug] Installing from source, unable to run from another folder

### ISSUE THREAD

**Issue by joaociocca** [laramies/theHarvester#926]
**Feature Request or Bug or Other**
Won't run from outside the installed folder.

**Describe the feature request or bug or other**
I'm doing some tests on not-Kali for stuff, and one of the tools I've tested was theHarvester. Since I couldn't just `apt install` I ended up here and found the instructions for [Option 3 - From Source](https://github.com/laramies/theHarvester/wiki/Installation#option-3---from-source).
When I run this from the installed folder, everything runs just fine. But if I try to call the script from somewhere else, it breaks on proxy_list

**To Reproduce**
Steps to reproduce the behaviour:
1. Install following the instructions on [Option 3 - From Source](https://github.com/laramies/theHarvester/wiki/Installation#option-3---from-source) on some folder, like `/home/user/theHarvester/`.
2. Switch to another folder, like `/home/user/AnotherFolder/`.
3. Try to run `python3 ~/theHarvester/theHarvester.py -h`.
4. Fail.

**Expected behaviour**
It should run as fine as if it was on the installed folder.

**Screenshots**
```bash
johnny@ciocca:~/SomeFolder$ python3 ~/theHarvester/theHarvester.py -h
Traceback (most recent call last):
  File "/home/johnny/theHarvester/theHarvester/lib/core.py", line 90, in proxy_list
    with open('/etc/theHarvester/proxies.yaml', 'r') as proxy_file:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/theHarvester/proxies.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnny/theHarvester/theHarvester/lib/core.py", line 94, in proxy_list
    with open('/usr/local/etc/theHarvester/proxies.yaml', 'r') as proxy_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/etc/theHarvester/proxies.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnny/theHarvester/theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/home/johnny/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/home/johnny/theHarvester/theHarvester/discovery/takeover.py", line 1, in <module>
    from theHarvester.lib.core import *
  File "/home/johnny/theHarvester/theHarvester/lib/core.py", line 233, in <module>
    class AsyncFetcher:
  File "/home/johnny/theHarvester/theHarvester/lib/core.py", line 234, in AsyncFetcher
    proxy_list = Core.proxy_list()
  File "/home/johnny/theHarvester/theHarvester/lib/core.py", line 97, in proxy_list
    with open('proxies.yaml', 'r') as proxy_file:
FileNotFoundError: [Errno 2] No such file or directory: 'proxies.yaml'
johnny@ciocca:~/SomeFolder$ 
```

**System Information (System that tool is running on):**
 - Ubuntu 20.04.3 LTS x86_64
 - Version [e.g. 2.7]

**Additional context**
I'm a total python noob, but I tried piecing together a solution searching around... one idea that hit me was something like adding these imports

```python
from pathlib import Path
from inspect import getsourcefile
from os.path import abspath
import os
```

and then changing `def proxylist()` to

```python
    def proxy_list() -> List:
        try:
            with open('/etc/theHarvester/proxies.yaml', 'r') as proxy_file:
                keys = yaml.safe_load(proxy_file)
        except FileNotFoundError:
            try:
                with open('/usr/local/etc/theHarvester/proxies.yaml', 'r') as proxy_file:
                    keys = yaml.safe_load(proxy_file)
            except FileNotFoundError:
                home_folder = str(Path(os.path.dirname(abspath(getsourcefile(lambda:0)))).parent.parent)
                proxies_file = home_folder+'/api-keys.yaml'
                with open(proxies_file, 'r') as proxy_file:
                    keys = yaml.safe_load(proxy_file)
                # with open('proxies.yaml', 'r') as proxy_file:
                #     keys = yaml.safe_load(proxy_file)
        http_list = [f'http://{proxy}' for proxy in keys['http']] if keys['http'] is not None else []
        return http_list
```

but this also fails...

```bash
johnny@ciocca:~/SomeFolder$ python3 ~/theHarvester/theHarvester.py -h
Traceback (most recent call last):
  File "/home/johnny/theHarvester/theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/home/johnny/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/home/johnny/theHarvester/theHarvester/discovery/takeover.py", line 1, in <module>
    from theHarvester.lib.core import *
  File "/home/johnny/theHarvester/theHarvester/lib/core.py", line 240, in <module>
    class AsyncFetcher:
  File "/home/johnny/theHarvester/theHarvester/lib/core.py", line 241, in AsyncFetcher
    proxy_list = Core.proxy_list()
  File "/home/johnny/theHarvester/theHarvester/lib/core.py", line 106, in proxy_list
    http_list = [f'http://{proxy}' for proxy in keys['http']] if keys['http'] is not None else []
KeyError: 'http'
johnny@ciocca:~/SomeFolder$ 
```

**Comment by NotoriousRebel** [comment]
Thank you for creating this issue, the logic for proxies.yaml will change to follow the logic for api-keys.yaml where it will also add a check for that file within your current working directory. I've run into this issue many times as well and just modify the proxies.yaml function to return [] when I don't use proxies.

**Comment by DrEliot** [comment]
I installed theharvester even with homebrew and i'm facing the same issue...

**Comment by L1ghtn1ng** [comment]
this should be fixed now with the move to pep517 as the backend
