### ISSUE TITLE
[Bug|Feature Request|Other] Short Description of Issue

### ISSUE THREAD

**Issue by CpoSaint** [laramies/theHarvester#960]
## Note we do not support installing theHarvester on andriod

**Feature Request or Bug or Other**
Feature Request | Bug | Other

**Describe the feature request or bug or other**
A clear and concise description of what the bug, feature request,
or other request is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: '...'
2. See error

**Expected behaviour**

**Screenshots**
If possible please add screenshots to help explain your problem.

**System Information (System that tool is running on):**
 - OS: [e.g. Windows10]
 - Version [e.g. 2.7]

**Additional context**
theHarvester -h
Traceback (most recent call last):
  File "/usr/bin/theHarvester", line 6, in <module>
    from theHarvester import __main__
  File "/usr/lib/python3/dist-packages/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/usr/lib/python3/dist-packages/theHarvester/discovery/takeover.py", line 1, in <module>
    from theHarvester.lib.core import *
  File "/usr/lib/python3/dist-packages/theHarvester/lib/core.py", line 6, in <module>
    import aiohttp
  File "/usr/lib/python3/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/lib/python3/dist-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
  

Im use kali when i open theHarvester this is what i get

**Comment by NotoriousRebel** [comment]
Try with the latest version of the tool and use a venv for requirements installation or just verify requirements.txt was installed successfully.

**Comment by L1ghtn1ng** [comment]
This is a kali issue
